version: '3'
services:
  web:
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ".:/app"
    working_dir: "/app"
    build: .
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    #for development we override command with live-reloading capabilities
    command: ["gunicorn", "--reload", "--worker-class", "eventlet", "-w", "1", "--access-logfile", "-", "-b", "0.0.0.0:8080", "app:app", "-t", "9999", "--error-logfile", "-"]
  db:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: okreads
