version: '3'
services:
  web:
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ".:/app"
    working_dir: "/app"
    build: .
    command: ["python", "app.py"]
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
